// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Bridge__NavMenuController from "./bridge/nav_menu_controller"
application.register("bridge--nav-menu", Bridge__NavMenuController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)
